### ISSUE TITLE
Can only use Push/Pull in DarkRP

### ISSUE THREAD

**Issue by Z0mbine** [generalwrex/precision-tool#7]
Yes, yes, I'm aware you probably dislike DarkRP's compatibility issues, but the only reason I'm asking is because I've witnessed other servers using the full tool, while fresh out of the box on a vanilla DarkRP server, attempting to use the other tools (parent, apply, slider...) yields no result. Not even an error. Would you happen to know why?

**Comment by generalwrex** [comment]
Closing this as it has been over a year, and noone else has confirmed ;)
