### ISSUE TITLE
Tool bugging on Linux GMod server

### ISSUE THREAD

**Issue by Yuri6037** [generalwrex/precision-tool#9]
Hello all,

So I'm using your tool for a long time now and on windows operating systems i had never any problem. But when I use it on a Linux GMod server, the tool still works fine, except when you Move/Rotate. When you click a prop, it becomes transparent like expected, however it does not follow your camera.

But you can still click on another location to move the prop. Now when the rotation system starts, the camera is not fixed like in windows, it still rotates, but the camera rotation won't block...

**Comment by generalwrex** [comment]
Closing this as it has been over a year, and no one else has confirmed. Also i have the tool running on a nix server atm and everything's working fine ;)
